# Generated by Django 6.0.5 on 2026-05-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dxf_file', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('Custom / Other', 'Custom / Other'), ('VRS', 'VRS'), ('Sign faces', 'Sign faces'), ('Sign posts', 'Sign posts'), ('Lighting columns', 'Lighting columns'), ('Traffic signals', 'Traffic signals'), ('Bollards', 'Bollards'), ('Road markings', 'Road markings'), ('Kerbs / edging', 'Kerbs / edging'), ('Gullies', 'Gullies'), ('Manholes / chambers', 'Manholes / chambers'), ('Drainage ditches', 'Drainage ditches'), ('Culverts / headwalls', 'Culverts / headwalls'), ('Utility covers', 'Utility covers'), ('Utility marker posts', 'Utility marker posts'), ('Fencing', 'Fencing'), ('Gates', 'Gates'), ('Trees', 'Trees'), ('Hedges', 'Hedges'), ('Overhead lines / poles', 'Overhead lines / poles'), ('Cabinets / comms boxes', 'Cabinets / comms boxes'), ('Bus stops / laybys', 'Bus stops / laybys'), ('Accesses / driveways', 'Accesses / driveways'), ('Junctions', 'Junctions'), ('Existing walls', 'Existing walls'), ('Retaining walls', 'Retaining walls'), ('Watercourses', 'Watercourses'), ('Embankments', 'Embankments'), ('Cuttings', 'Cuttings'), ('Verge edges', 'Verge edges'), ('Pavement defects', 'Pavement defects'), ('Edge break-up', 'Edge break-up'), ('Ponding / drainage issues', 'Ponding / drainage issues')], max_length=100)),
                ('custom_feature_type', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side'), ('BOTH', 'Both Sides'), ('NA', 'Not Applicable')], max_length=10)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], max_length=10)),
                ('offset_from_edge_m', models.FloatField(default=0.0)),
                ('distance_along_edge_m', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('chainage_m', models.FloatField()),
                ('distance_from_alignment_m', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='site_app.alignment')),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chainage_m'],
            },
        ),
        migrations.CreateModel(
            name='PassingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_id', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side')], max_length=10)),
                ('status', models.CharField(choices=[('Existing', 'Existing'), ('New', 'New')], max_length=10)),
                ('mid_chainage_m', models.FloatField()),
                ('mid_latitude', models.FloatField()),
                ('mid_longitude', models.FloatField()),
                ('mid_easting', models.FloatField()),
                ('mid_northing', models.FloatField()),
                ('width_m', models.FloatField(default=0.0)),
                ('length_m', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_places', to='site_app.alignment')),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passing_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mid_chainage_m'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('engineer', 'Field Engineer'), ('reviewer', 'Reviewer (Read Only)')], default='engineer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
