# Generated by Django 5.2 on 2026-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='dxf_upload',
            field=models.FileField(blank=True, null=True, upload_to='dxf_files/'),
        ),
        migrations.AddField(
            model_name='featurecapture',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passingplace',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passingplace',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='featurecapture',
            name='feature_type',
            field=models.CharField(choices=[('Accesses / driveways', 'Accesses / driveways'), ('Bollards', 'Bollards'), ('Bus stops / laybys', 'Bus stops / laybys'), ('Cabinets / comms boxes', 'Cabinets / comms boxes'), ('Culverts / headwalls', 'Culverts / headwalls'), ('Cuttings', 'Cuttings'), ('Drainage ditches', 'Drainage ditches'), ('Edge break-up', 'Edge break-up'), ('Embankments', 'Embankments'), ('Existing walls', 'Existing walls'), ('Fencing', 'Fencing'), ('Gates', 'Gates'), ('Gullies', 'Gullies'), ('Hedges', 'Hedges'), ('Junctions', 'Junctions'), ('Kerbs / edging', 'Kerbs / edging'), ('Lighting columns', 'Lighting columns'), ('Manholes / chambers', 'Manholes / chambers'), ('Overhead lines / poles', 'Overhead lines / poles'), ('Pavement defects', 'Pavement defects'), ('Ponding / drainage issues', 'Ponding / drainage issues'), ('Retaining walls', 'Retaining walls'), ('Road markings', 'Road markings'), ('Sign faces', 'Sign faces'), ('Sign posts', 'Sign posts'), ('Traffic signals', 'Traffic signals'), ('Trees', 'Trees'), ('Utility covers', 'Utility covers'), ('Utility marker posts', 'Utility marker posts'), ('Verge edges', 'Verge edges'), ('VRS', 'VRS'), ('Watercourses', 'Watercourses'), ('Custom / Other', 'Custom / Other')], max_length=100),
        ),
    ]
