# Generated by Django 5.2 on 2026-05-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alignment_dxf_upload_featurecapture_gps_accuracy_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecapture',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='passingplace',
            name='photo',
        ),
        migrations.CreateModel(
            name='FeaturePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/features/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='site_app.featurecapture')),
            ],
        ),
        migrations.CreateModel(
            name='PassingPlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/passing_places/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('passing_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='site_app.passingplace')),
            ],
        ),
    ]
