# Generated by Django 5.2 on 2026-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_remove_featurecapture_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecapture',
            name='entry_method',
            field=models.CharField(choices=[('GPS', 'GPS Capture'), ('Manual', 'Manual Entry')], default='GPS', max_length=10),
        ),
        migrations.AddField(
            model_name='passingplace',
            name='entry_method',
            field=models.CharField(choices=[('GPS', 'GPS Capture'), ('Manual', 'Manual Entry')], default='GPS', max_length=10),
        ),
    ]
