# Generated by Django 5.2 on 2026-06-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_featurecapture_entry_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecapture',
            name='feature_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
