# Generated by Django 5.2 on 2026-06-08 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_featurecapture_feature_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.CharField(blank=True, default='', max_length=20)),
                ('structure_name', models.CharField(blank=True, max_length=200)),
                ('feature_type', models.CharField(choices=[('Arch Bridge', 'Arch Bridge'), ('Gabions', 'Gabions'), ('Multi-Cell Structure', 'Multi-Cell Structure'), ('Roadside Structure', 'Roadside Structure'), ('Bridge', 'Bridge'), ('Arch', 'Arch'), ('Abutment', 'Abutment'), ('Approaches', 'Approaches'), ('Beam', 'Beam'), ('Cill-Unit', 'Cill-Unit'), ('Column / Pier', 'Column / Pier'), ('Culvert', 'Culvert'), ('Cutting', 'Cutting'), ('Embankment', 'Embankment'), ('Headwall', 'Headwall'), ('Retaining Wall', 'Retaining Wall'), ('Watercourse', 'Watercourse'), ('Wingwall', 'Wingwall'), ('Other', 'Other')], max_length=50)),
                ('custom_feature_type', models.CharField(blank=True, max_length=100)),
                ('num_spans', models.IntegerField(default=1)),
                ('span_length_m', models.FloatField(default=0.0)),
                ('vehicle_clearance_m', models.FloatField(default=0.0)),
                ('parapet_height_m', models.FloatField(default=0.0)),
                ('parapet_width_m', models.FloatField(default=0.0)),
                ('footpath_width_m', models.FloatField(default=0.0)),
                ('material', models.CharField(choices=[('Concrete', 'Concrete'), ('Masonry', 'Masonry'), ('Steel', 'Steel'), ('Timber', 'Timber'), ('Other', 'Other')], max_length=20)),
                ('custom_material', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side'), ('N/A', 'Not Applicable')], max_length=10)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10)),
                ('offset_from_edge_m', models.FloatField(default=0.0)),
                ('distance_along_edge_m', models.FloatField(default=0.0)),
                ('recommended_action', models.CharField(choices=[('No Action', 'No Action'), ('Monitor', 'Monitor'), ('Protect', 'Protect'), ('Modify', 'Modify'), ('Replace', 'Replace')], default='No Action', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chainage_m', models.FloatField()),
                ('distance_from_alignment_m', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('gps_accuracy_m', models.FloatField(blank=True, null=True)),
                ('entry_method', models.CharField(choices=[('GPS', 'GPS Capture'), ('Manual', 'Manual Entry')], default='GPS', max_length=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='site_app.alignment')),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chainage_m'],
            },
        ),
        migrations.CreateModel(
            name='StructurePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/structures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='site_app.structure')),
            ],
        ),
    ]
