# Generated by Django 5.2 on 2026-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_structure_structurephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='custom_material',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='distance_along_edge_m',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='footpath_width_m',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='material',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='num_spans',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='offset_from_edge_m',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='parapet_height_m',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='parapet_width_m',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='span_length_m',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='vehicle_clearance_m',
        ),
        migrations.AddField(
            model_name='structure',
            name='abutment_brick_b_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='abutment_brick_d_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='abutment_length_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='approx_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='arch_barrel_cracking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='structure',
            name='arch_barrel_joints',
            field=models.CharField(blank=True, choices=[('pointed_good', 'Pointed joints in good condition'), ('unpointed_poor', 'Un-pointed joints, poor condition and insufficiently filled to 12.5mm from edge'), ('10pct_unfilled', 'With 10% of the thickness insufficiently filled'), ('10_30pct_unfilled', 'Insufficiently filled for more than 10% but less than 30% of the thickness of the barrel')], max_length=30),
        ),
        migrations.AddField(
            model_name='structure',
            name='arch_brick_b_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='arch_brick_d_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='bed_joint_thickness',
            field=models.CharField(blank=True, choices=[('up_to_6mm', 'Widths up to 6mm'), ('6mm_to_12.5mm', 'Widths between 6mm and 12.5mm'), ('over_12.5mm', 'Widths over 12.5mm')], max_length=20),
        ),
        migrations.AddField(
            model_name='structure',
            name='bed_thickness_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='defect_direction',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='structure',
            name='defect_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='structure',
            name='defect_thickness',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='structure',
            name='distance_along_edge_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='footpath_width_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='mortar_barrel',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Loose_Friable', 'Loose or Friable')], max_length=20),
        ),
        migrations.AddField(
            model_name='structure',
            name='mortar_strength',
            field=models.CharField(blank=True, choices=[('Crumbly', 'Crumbly'), ('Solid', 'Solid')], max_length=20),
        ),
        migrations.AddField(
            model_name='structure',
            name='offset_from_edge_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='parapet_height_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='parapet_thickness_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='rise_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='rise_quarter_points_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='span_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='type_of_stone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='structure',
            name='vehicle_clearance_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='condition',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='structure',
            name='feature_type',
            field=models.CharField(choices=[('Bridge', 'Bridge'), ('Arch Bridge', 'Arch Bridge'), ('Gabions', 'Gabions'), ('Multi-Cell Structure', 'Multi-Cell Structure'), ('Roadside Structure', 'Roadside Structure'), ('Arch', 'Arch'), ('Abutment', 'Abutment'), ('Approaches', 'Approaches'), ('Beam', 'Beam'), ('Cill-Unit', 'Cill-Unit'), ('Column / Pier', 'Column / Pier'), ('Culvert', 'Culvert'), ('Cutting', 'Cutting'), ('Embankment', 'Embankment'), ('Headwall', 'Headwall'), ('Retaining Wall', 'Retaining Wall'), ('Watercourse', 'Watercourse'), ('Wingwall', 'Wingwall'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='structure',
            name='recommended_action',
            field=models.CharField(blank=True, choices=[('No Action', 'No Action'), ('Monitor', 'Monitor'), ('Protect', 'Protect'), ('Modify', 'Modify'), ('Replace', 'Replace')], max_length=20),
        ),
        migrations.AlterField(
            model_name='structure',
            name='side',
            field=models.CharField(blank=True, choices=[('LHS', 'Left Hand Side'), ('RHS', 'Right Hand Side'), ('N/A', 'Not Applicable')], max_length=10),
        ),
    ]
